#targetPlatform: COMPOSE or SWIFTUI
targetPlatform=COMPOSE
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/communication/httpsms-main/android/app/src/main/res
resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/business/openshop.io-android-master/app/src/main/res