#targetPlatform: COMPOSE or SWIFTUI
targetPlatform=SWIFTUI
# FIXME business
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/business/show_openshop/app/src/main/res

# communication
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/communication/show_chatsecureandroid//app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/communication/show_httpsms/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/communication/show_kissproxy/app/src/main/res

# FIXME edu
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/education/show_GivesMeHope/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/education/show_Hackathon/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/education/show_SayHi/app/src/main/res


# FIXME finance
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/finance/show_coins/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/finance/show_gnucash/app/src/main/res


# FIXME health
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/health/show_medicalData/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/health/show_heartRateMonitor/app/src/main/res


# FIXME media
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/media/show_AwkwardRatings/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/media/show_smartTube/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/media/show_SoundRecorder/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/media/show_vineyard/app/src/main/res


# FIXME news
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/news/show_hn/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/news/show_Ganhuo/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/news/show_Rivers/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/news/show_hex/app/src/main/res

# FIXME prod
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/productivity/show_CarbonContacts/app/src/main/res
resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/productivity/show_EverMemo/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/productivity/show_habitica/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/productivity/show_habito/app/src/main/res


# FIXME social
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/social/show_Cotable/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/social/show_FishChat/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/social/show_BlackLight/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/social/show_CNode/app/src/main/res

# FIXME tool
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/tools/show_ContentProvider/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/tools/show_connectBot/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/tools/show_Catcher/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/tools/show_Bitocle/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/tools/show_cleanStatusBar/app/src/main/res
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/tools/show_BetterBatteryStats/app/src/main/res



