#targetPlatform: COMPOSE or SWIFTUI
targetPlatform=COMPOSE
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/business/openshop.io-android-master/app/src/main/res



# FIXME edu
#resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/education/show_Hackathon/app/src/main/res


# FIXME finance
resourcePath=/Users/gaoyi/AndroidStudioProjects/guimigration_datasets/finance/show_coins/app/src/main/res

